---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - konflux-ci.mintmaker.redhat.com
  resources:
  - mintmakerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konflux-ci.mintmaker.redhat.com
  resources:
  - mintmakerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - konflux-ci.mintmaker.redhat.com
  resources:
  - mintmakerconfigs/status
  verbs:
  - get
  - patch
  - update
