name: "Validate renovate.json config file"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-user-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: konflux-ci/renovate-config-validator-action@1891cfbf5e12443366e799383d6b8141310883b8 # main
        with:
          config_file: .github/renovate.json

  validate-backend-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: konflux-ci/renovate-config-validator-action@1891cfbf5e12443366e799383d6b8141310883b8 # main
        with:
          config_file: config/renovate/renovate.json
