name: "Validate renovate.json config file"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate-user-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: konflux-ci/renovate-config-validator-action@772ce0f2d37cd13ad80408a4902c7a17f3191e3a # main
        with:
          config_file: .github/renovate.json

  validate-backend-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: konflux-ci/renovate-config-validator-action@772ce0f2d37cd13ad80408a4902c7a17f3191e3a # main
        with:
          config_file: config/renovate/renovate.json
